apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-store-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: prod.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mini-store-service
            port:
              number: 80