apiVersion: v1
kind: Service
metadata:
  name: mini-store-service
  namespace: prod
spec:
  type: NodePort   
  selector:
    app: mini-store
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30083