apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-store-deployment
  namespace: dev 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-store
  template:
    metadata:
      labels:
        app: mini-store
    spec:
      containers:
      - name: mini-store
        image: samirbch/mini-store:v13
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongos-svc.dev.svc.cluster.local:27018/shop"
        - name: REDIS_HOST
          value: "redis.dev.svc.cluster.local"
      imagePullSecrets:
      - name: docker-secret   # ‚Üê ajouter ici
